### ISSUE TITLE
dependency issue: missing File resource

### ISSUE THREAD

**Issue by tiernap** [tohuwabohu/puppet-roundcube#9]
i get the following error:

`Could not find dependency File[/opt] for Archive[/var/cache/puppet/archives/roundcubemail-1.3.6-complete.tar.gz] at /tmp/vagrant-puppet/modules-c39541f238d7892abe5b5fd1f6535899/roundcube/manifests/install.pp:20`

i cannot find the file resource anywhere in the module, is it missing?

**Comment by tohuwabohu** [comment]
Ah right. That's a left-over of using the old archive provider. You should get this working by adding

```
file { '/opt':
  ensure => directory,
}
```

to your puppet manifest.

Adding this to the module itself is hard because it may be defined by other modules as well. Using something like `ensure_resource` can be subject to a race condition which is also not great.
